webtalk_init -webtalk_dir C:/Users/GlommyHand/Desktop/Workstation/Git/Bus_CPU/Five-level-flow-CPU.sim/sim_1/behav/xsim.dir/testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 29 02:13:14 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1756540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7bd9d2e8-1b23-4637-b5d3-c7f67c439ce0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "88f75919ec2a4dcbb064f22495e181f7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "30" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "571 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "44 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "1349" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "638" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "85" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.73_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "108260_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3928716923 -regid "" -xml C:/Users/GlommyHand/Desktop/Workstation/Git/Bus_CPU/Five-level-flow-CPU.sim/sim_1/behav/xsim.dir/testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/GlommyHand/Desktop/Workstation/Git/Bus_CPU/Five-level-flow-CPU.sim/sim_1/behav/xsim.dir/testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/GlommyHand/Desktop/Workstation/Git/Bus_CPU/Five-level-flow-CPU.sim/sim_1/behav/xsim.dir/testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
