# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/inst_mem/inst_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_mem || ORIG_REF_NAME==inst_mem}]
