# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Xilinx/singel_cpu/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/singel_cpu/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Xilinx/MIPS_2017/proj_4.cache/ip [current_project]
set_property ip_output_repo d:/Xilinx/singel_cpu/project_1/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/imports/new/mipstest.coe
read_verilog D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/imports/new/defines.vh
read_verilog -library xil_defaultlib {
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/adder.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/alu.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/imports/new/alu_decoder.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/imports/new/controller.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/datapath.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/eqcmp.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/flopenr.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/flopenrc.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/flopr.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/floprc.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/hazard.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/hilo_reg.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/imports/new/main_decoder.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/mips.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/mux2.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/mux3.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/reg_file.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/signext.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/new/sl2.v
  D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/imports/new/top.v
}
read_ip -quiet D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all d:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/ip/inst_mem/inst_mem_ooc.xdc]
set_property is_locked true [get_files D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/ip/inst_mem/inst_mem.xci]

read_ip -quiet D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all d:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc]
set_property is_locked true [get_files D:/Xilinx/singel_cpu/project_1/project_1.srcs/sources_1/ip/data_mem/data_mem.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
